pipelines:
  release:
    - task: download
    - task: update-formula
      depends_on: download

tasks:
  download:
    command:
      - wget -N https://github.com/taskctl/taskctl/releases/download/${ARGS}/taskctl-darwin-amd64.tar.gz

  update-formula:
    command:
      - sed -i '' '/Version:/s/".*"/"'${ARGS}'"/' cmd/cmd.go
      - sed -i '' '/  sha256/s/".*"/"'$(shasum -a256 taskctl-darwin-amd64.tar.gz | awk '{print $1}')'"/' taskctl.rb
